# Generated by Django 3.0.3 on 2020-02-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hero',
            options={'verbose_name_plural': 'Heroes'},
        ),
        migrations.RemoveField(
            model_name='game',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='team',
            name='side',
        ),
        migrations.AddField(
            model_name='game',
            name='attribute',
            field=models.SmallIntegerField(choices=[(1, 'Strength'), (2, 'Agility'), (3, 'Intelligence')], default=1),
        ),
        migrations.AddField(
            model_name='hero',
            name='attribute',
            field=models.SmallIntegerField(choices=[(1, 'Strength'), (2, 'Agility'), (3, 'Intelligence')], default=1),
        ),
        migrations.AddField(
            model_name='team',
            name='attribute',
            field=models.SmallIntegerField(choices=[(1, 'Radiant'), (2, 'Dire')], default=1),
        ),
    ]
