# Generated by Django 3.0.3 on 2020-02-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20200228_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='attribute',
            new_name='side',
        ),
        migrations.RemoveField(
            model_name='game',
            name='attribute',
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.SmallIntegerField(choices=[(1, 'Radiant'), (2, 'Dire')], default=1),
        ),
    ]
