# Generated by Django 3.0.3 on 2020-02-28 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20200228_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='team',
        ),
        migrations.AddField(
            model_name='team',
            name='player1',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='games.RelationsGroupHeroPlayer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='player2',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='games.RelationsGroupHeroPlayer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='relationsgroupheroplayer',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Group'),
        ),
    ]
