# Generated by Django 3.0.4 on 2020-03-06 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numMembers', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('attribute', models.SmallIntegerField(choices=[(1, 'Strength'), (2, 'Agility'), (3, 'Intelligence')], default=1)),
            ],
            options={
                'verbose_name_plural': 'Heroes',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RelationsGroupHeroPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('networth', models.IntegerField()),
                ('kda', models.FloatField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Group')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Hero')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.SmallIntegerField(choices=[(1, 'Radiant'), (2, 'Dire')], default=1)),
                ('kills', models.SmallIntegerField()),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='games.RelationsGroupHeroPlayer')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='games.RelationsGroupHeroPlayer')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.SmallIntegerField(choices=[(1, 'Radiant'), (2, 'Dire')], default=1)),
                ('date', models.DateField()),
                ('dire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dire', to='games.Team')),
                ('radiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radiant', to='games.Team')),
            ],
        ),
    ]
